navigation:
  - title: News
    url: /news/

  - title: Gallery
    url: /gallery/

  - title: Discography
    url: /discography/

  - title: Members
    url: /members/

  - title: About
    url: /about/